version: '3'
services:
  robot-runner:
    container_name: robot-runner
    image: ppodgorsek/robot-framework:latest
    volumes:
      - ./robot-tests:/opt/robotframework/tests
      - ./output-local:/opt/robotframework/reports
    environment:
      PYTHONWARNINGS: "ignore:Unverified HTTPS request"
