apiVersion: v1
kind: Pod
metadata:
  name: robotframework-demo-pod
  labels:
    app: robotframework-demo
spec:
  containers:
  - name: run-robot-tests
    image: ppodgorsek/robot-framework:latest
    env:
    - name: PYTHONWARNINGS
      value: "ignore:Unverified HTTPS request"
    # command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    volumeMounts:
    - mountPath: /opt/robotframework/tests
      name: git
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "0.5"
        memory: "500Mi"
  restartPolicy: Never
  initContainers:
  - name: init-clone-repo
    image: alpine/git
    args:
        - clone
        - --single-branch
        - --
        - https://github.com/Nilsty/robotframework-demo
        - /var/lib/data
    volumeMounts:
    - name: git
      mountPath: /var/lib/data
  volumes:
  - emptyDir: {}
    name: git
